spring:
  application:
    name: demo-spring-boot-mail
  #邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: xigua311@163.com #发送邮件的邮箱地址
    password: TRACSQATMTOUAESB #客户端授权码，不是邮箱密码,网易的是自己设置的
    // from: demo@demo.com # 发送邮件的地址，和上面username一致  不一致会报异常：org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 553 Mail from must equal authorized user
    from: xigua311@163.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8